# TODO rename to maas-repose?
name             'wrapper-repose'
maintainer       'Rackspace'
maintainer_email 'YOUR_EMAIL'
license          'Apache 2.0'
description      'Installs/Configures wrapper-repose'
long_description 'Installs/Configures wrapper-repose'
version          '0.1.0'
depends          'repose'
depends          'apt'
depends          'java'
