name 'wrapper-repose'
maintainer 'Rackspace'
maintainer_email 'sfo-devops@lists.rackspace.com'
license 'Apache 2.0'
description 'Installs/Configures wrapper-repose'
long_description 'Installs/Configures wrapper-repose'
version '0.2.11'

depends 'apt'
depends 'java'
depends 'repose'
